name: format_and_test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-ubuntu:
    runs-on: onprem
    timeout-minutes: 45
    strategy:
      matrix:
        docker-image: ["python:3.7", "python:3.8", "python:3.9"]
    steps:
    - name: Checkout mava
      uses: actions/checkout@v2
    - name: Run tests in docker
      run: |
        docker run /bin/bash ./bash_scripts/tests.sh
