name: format_and_test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-ubuntu:
    runs-on: onprem
    timeout-minutes: 45
    strategy:
      matrix:
        python-version: [3.6.13, 3.7.1, 3.8.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Format code
        run: |
          pip install .[testing_formatting]
          # Check code follows black formatting.
          black --check .
          # stop the build if there are Python syntax errors or undefined names
          flake8 .  --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --statistics
      - name: Check types with mypy
        run: |
          mypy --exclude '(docs|build)/$' .
      - name: Test with pytest and get code coverage
        run: |
          ./bash_scripts/tests.sh
      - name: Check docstring code coverage
        run: |
          interrogate -c pyproject.toml
