name: push-docker-container

on: push
# on:
#   push:
#     branches:
#       - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      -
        name: Build and push tf-core
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:tf-core-latest,instadeepct/mava:tf-core-${{ steps.vars.outputs.sha_short }}
          target: tf-core

      -
        name: Build and push pz
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:pz-latest,instadeepct/mava:pz-${{ steps.vars.outputs.sha_short }}
          target: pz

      -
        name: Build and push sc2
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:sc2-latest,instadeepct/mava:sc2-${{ steps.vars.outputs.sha_short }}
          target: sc2

      -
        name: Build and push flatland
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:flatland-latest,instadeepct/mava:flatland-${{ steps.vars.outputs.sha_short }}
          target: flatland

      -
        name: Build and push robocup
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:robocup-latest,instadeepct/mava:robocup-${{ steps.vars.outputs.sha_short }}
          target: robocup

      -
        name: Build and push openspiel
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:openspiel-latest,instadeepct/mava:openspiel-${{ steps.vars.outputs.sha_short }}
          target: openspiel

      -
        name: Build and push meltingpot
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: instadeepct/mava:meltingpot-latest,instadeepct/mava:meltingpot-${{ steps.vars.outputs.sha_short }}
          target: meltingpot
